// Star Wars Planeten-Datenbank
// Grid-Koordinaten: Buchstabe (X-Achse, A-V) + Zahl (Y-Achse, 1-20)
// Pixel-Koordinaten normalisiert auf 1150x1150 Bildgröße (0.0 - 1.0)
// Quellen: SW Galaxy Map (starwars.com), Essential Atlas, Wookieepedia

const PLANETS = [
  // ── DEEP CORE ──────────────────────────────────────────────────────
  { name: "Coruscant",      grid: "L-9",  x: 0.4817, y: 0.4189, region: "Deep Core",    terrain: "Stadtplanet",             desc: "Galaktische Hauptstadt, vollständig urbanisiert. Nullpunkt des galaktischen Koordinatensystems." },
  { name: "Byss",           grid: "K-11", x: 0.4631, y: 0.5035, region: "Deep Core",    terrain: "Canyons, Plateaus",        desc: "Geheimnisvoller Thronsitz von Imperator Palpatine (Legends). Stark mit der dunklen Seite verbunden." },
  { name: "Prakith",        grid: "J-11", x: 0.4642, y: 0.4591, region: "Deep Core",    terrain: "Wälder, Berge",            desc: "Isolierter Planet des Deep Core. Sitz des Moff Tarkin vor seiner Karriere (Legends)." },
  { name: "Tython",         grid: "L-9",  x: 0.4837, y: 0.4543, region: "Deep Core",    terrain: "Wälder, Gebirge, Flüsse",  desc: "Geburtsstätte des Jedi-Ordens. Einer der heiligsten Orte der Jedi." },
  { name: "Korriban",       grid: "R-5",  x: 0.7499, y: 0.1924, region: "Outer Rim",    terrain: "Wüste, Canyons",           desc: "Uralte Heimatwelt der Sith. Grabstätte zahlloser Sith-Lords. Auch bekannt als Moraband." },

  // ── CORE WORLDS ────────────────────────────────────────────────────
  { name: "Alderaan",       grid: "M-10", x: 0.5432, y: 0.4211, region: "Core Worlds",  terrain: "Wälder, Berge, Ebenen",    desc: "Friedliche Heimatwelt von Prinzessin Leia. Zerstört durch den Todesstern. Berühmt für Kunst und Kultur." },
  { name: "Corellia",       grid: "M-11", x: 0.5495, y: 0.5078, region: "Core Worlds",  terrain: "Wälder, Ebenen, Ozeane",   desc: "Heimatwelt von Han Solo und Wedge Antilles. Berühmt für Schiffsbau und Piloten." },
  { name: "Chandrila",      grid: "L-9",  x: 0.505, y: 0.4012, region: "Core Worlds",  terrain: "Wälder, Ebenen, Ozeane",   desc: "Heimatwelt von Mon Mothma. Gründungsort der Neuen Republik nach dem Galaktischen Bürgerkrieg." },
  { name: "Hosnian Prime",  grid: "L-9",  x: 0.503, y: 0.4025, region: "Core Worlds",  terrain: "Städtisch",                desc: "Hauptsitz der Neuen Republik. Zerstört durch die Starkiller-Basis." },
  { name: "Anaxes",         grid: "L-10", x: 0.4996, y: 0.405, region: "Core Worlds",  terrain: "Wälder, Berge",            desc: "Wichtiger Militärstützpunkt der Republik und des Imperiums. Bedeutende Flottenbasis." },
  { name: "Brentaal IV",    grid: "L-10", x: 0.5088, y: 0.4033, region: "Core Worlds",  terrain: "Städtisch, Ebenen",        desc: "Wichtiger Handelsplanet an der Perlemian Trade Route." },
  { name: "Carida",         grid: "M-10", x: 0.5484, y: 0.4539, region: "Core Worlds",  terrain: "Hochländer, Wälder",       desc: "Heimat der berühmtesten Imperiums-Akademie für Sturmtruppen." },

  // ── COLONIES ───────────────────────────────────────────────────────
  { name: "Cato Neimoidia", grid: "N-11", x: 0.5748, y: 0.4843, region: "Colonies",     terrain: "Wälder, Hängebrücken-Städte", desc: "Heimatwelt der Neimoidier. Brücken-Städte hängen zwischen Felsformationen." },
  { name: "Abregado-rae",   grid: "L-11", x: 0.48, y: 0.5701, region: "Colonies",     terrain: "Ebenen, Städte",           desc: "Bedeutender Handels- und Raumhafen-Planet." },

  // ── INNER RIM ──────────────────────────────────────────────────────
  { name: "Onderon",        grid: "P-11", x: 0.6794, y: 0.5001, region: "Inner Rim",    terrain: "Dschungel, Wälder",        desc: "Walled cities protect against jungle beasts. Site of conflict during Clone Wars and Rebellion." },
  { name: "Thyferra",       grid: "M-11", x: 0.5092, y: 0.6302, region: "Inner Rim",    terrain: "Dschungel",                desc: "Einzige Quelle von Bacta, dem wichtigsten Heilmittel der Galaxis." },

  // ── EXPANSION REGION ───────────────────────────────────────────────
  { name: "Malastare",      grid: "J-13", x: 0.4131, y: 0.5979, region: "Expansion Region", terrain: "Wüste, Ebenen",        desc: "Heimatwelt der Dug. Wichtige Podrace-Strecke. Große Treibstoffvorkommen." },

  // ── MID RIM ────────────────────────────────────────────────────────
  { name: "Naboo",          grid: "O-17", x: 0.6217, y: 0.76, region: "Mid Rim",       terrain: "Ebenen, Wälder, Seen",     desc: "Heimatwelt von Padmé Amidala und Kaiser Palpatine. Landschaftlich wunderschön, geteilt zwischen Naboo und Gungan." },
  { name: "Kashyyyk",       grid: "P-9",  x: 0.6891, y: 0.4113, region: "Mid Rim",       terrain: "Waldplanet (Riesenbäume)", desc: "Heimatwelt der Wookiees. Dichte Wälder aus riesigen Wroshyr-Bäumen. Heimat von Chewbacca." },
  { name: "Rodia",          grid: "Q-13", x: 0.7428, y: 0.7403, region: "Mid Rim",       terrain: "Dschungel, Sümpfe",        desc: "Heimatwelt der Rodier. Jagtplanet. Greedo stammte von hier." },
  { name: "Ord Mantell",    grid: "L-9",  x: 0.4823, y: 0.2956, region: "Mid Rim",       terrain: "Hügel, Ebenen, Ozeane",   desc: "Bedeutender Handelsplanet. Han Solo traf hier auf einen Kopfgeldjäger zwischen ANH und ESB." },
  { name: "Takodana",       grid: "J-9",  x: 0.3837, y: 0.7315, region: "Mid Rim",       terrain: "Wälder, Seen",             desc: "Heimat von Maz Kanata und ihrer Burg. Einer der letzten bewaldeten Planeten." },
  { name: "Boz Pity",       grid: "S-9",  x: 0.7906, y: 0.388, region: "Mid Rim",       terrain: "Canyons, Wüste, Berge",    desc: "Der 'Friedhofsplanet'. Schauplatz einer großen Klonkriegsschlacht." },
  { name: "Mon Cala",       grid: "U-7",  x: 0.9123, y: 0.3135, region: "Mid Rim",       terrain: "Ozean",                    desc: "Heimatwelt der Mon Calamari und Quarren. Admiral Ackbar stammte von hier. Lieferte der Rebellion Sternzerstörer." },
  { name: "Bothawui",       grid: "R-8",  x: 0.7537, y: 0.6276, region: "Mid Rim",       terrain: "Städte, Wälder",           desc: "Heimatwelt der Bothaner. Berühmt für ihr Spionagenetz. Bothanerspione starben für die Pläne des Todessterns II." },
  { name: "Ithor",          grid: "N-8",  x: 0.5936, y: 0.3557, region: "Mid Rim",       terrain: "Dschungel",                desc: "Heilige Welt der Ithorier. Keine Landung auf der Oberfläche erlaubt – Leben in schwebenden Städten." },

  // ── OUTER RIM ──────────────────────────────────────────────────────
  { name: "Tatooine",       grid: "R-16", x: 0.758, y: 0.742, region: "Outer Rim",    terrain: "Wüste",                    desc: "Doppelsonnen-Wüstenplanet. Heimatwelt von Anakin und Luke Skywalker. Beherrscht von Jabba dem Hutten." },
  { name: "Hoth",           grid: "K-18", x: 0.4398, y: 0.831, region: "Outer Rim",    terrain: "Eis und Schnee",           desc: "Gefrorener Planet. Standort von Echo Base, dem Rebellenstützpunkt. Schauplatz der berühmten Eisschlacht." },
  { name: "Dagobah",        grid: "M-21", x: 0.5507, y: 0.8759, region: "Outer Rim",    terrain: "Sümpfe, Dschungel",        desc: "Sumpfplanet. Verbannungsort von Meister Yoda. Stark mit der hellen Seite der Macht verbunden." },
  { name: "Bespin",         grid: "K-18", x: 0.4399, y: 0.8264, region: "Outer Rim",    terrain: "Gasriese",                 desc: "Gasriese mit schwebender Wolkenstadt. Tibanna-Gas-Abbau. Luke verlor hier seine Hand gegen Darth Vader." },
  { name: "Endor",          grid: "H-16", x: 0.3328, y: 0.7475, region: "Outer Rim",    terrain: "Wälder (Mond)",            desc: "Bewaldeter Mond. Heimat der Ewoks. Ort der entscheidenden Schlacht von Endor und des Todes von Palpatine." },
  { name: "Geonosis",       grid: "R-17", x: 0.7596, y: 0.7441, region: "Outer Rim",    terrain: "Wüste, Felsen",            desc: "Heimatwelt der Geonosianer. Ort der ersten Klonkriegsschlacht. Erste Produktionsstätte des Todessterns." },
  { name: "Utapau",         grid: "P-19", x: 0.5679, y: 0.8928, region: "Outer Rim",    terrain: "Sinkhole-Welt",            desc: "Planet voller Krater und Sinkhole-Städte. Obi-Wan Kenobi besiegte hier General Grievous." },
  { name: "Mustafar",       grid: "R-17", x: 0.4871, y: 0.894, region: "Outer Rim",    terrain: "Lava, Vulkane",            desc: "Vulkanischer Lavaplanet. Ort des epischen Duells zwischen Obi-Wan Kenobi und Anakin Skywalker." },
  { name: "Kessel",         grid: "R-16", x: 0.7761, y: 0.749, region: "Outer Rim",    terrain: "Wüste, Minen",             desc: "Berühmter Spice-Minenplanet. Han Solo machte den Kessel-Run in weniger als 12 Parsec." },
  { name: "Jakku",          grid: "L-19", x: 0.3806, y: 0.5854, region: "Outer Rim",    terrain: "Wüste",                    desc: "Entlegener Wüstenplanet. Heimat von Rey. Ort der Entscheidungsschlacht des Galaktischen Bürgerkriegs." },
  { name: "Yavin IV",       grid: "O-6",  x: 0.6396, y: 0.2567, region: "Outer Rim",    terrain: "Dschungel (Mond)",         desc: "Dschungelmond. Erster Standort der Rebellionsbasis. Ort der legendären Zerstörung des ersten Todessterns." },
  { name: "Scarif",         grid: "Q-20", x: 0.7978, y: 0.6833, region: "Outer Rim",    terrain: "Tropische Inseln",         desc: "Imperiale Zitadelle mit dem Todesstern-Datenspeicher. Rogue One stahl hier die Pläne." },
  { name: "Jedha",          grid: "M-13", x: 0.335, y: 0.4541, region: "Outer Rim",    terrain: "Wüste, heilige Stätten",   desc: "Kleiner Wüstenmond mit tiefer spiritueller Bedeutung. Kyber-Kristall-Vorkommen. Teilweise zerstört." },
  { name: "Eadu",           grid: "N-14", x: 0.8716, y: 0.4355, region: "Outer Rim",    terrain: "Felsen, Regen, Stürme",    desc: "Imperiale Forschungseinrichtung für Kyber-Kristallwaffen. Düsterer, sturmgeplagter Planet." },
  { name: "Lah'mu",         grid: "N-14", x: 0.5929, y: 0.6529, region: "Outer Rim",    terrain: "Schwarz-weiße Felder",     desc: "Abgelegener Planet. Versteck der Erso-Familie vor dem Imperium." },
  { name: "Mandalore",      grid: "O-7",  x: 0.6391, y: 0.2859, region: "Outer Rim",    terrain: "Wüste (ehemals Wälder)",   desc: "Heimatwelt der Mandalorianer. Durch Kriege verwüstet. Moff Gideon besaß das Darksaber." },
  { name: "Lothal",         grid: "P-17", x: 0.6862, y: 0.8092, region: "Outer Rim",    terrain: "Grasebenen, Wälder",       desc: "Imperiale Besatzungsplanet. Heimat von Ezra Bridger. Schauplatz der Ereignisse aus Rebels." },
  { name: "Ryloth",         grid: "O-10", x: 0.7709, y: 0.7853, region: "Outer Rim",    terrain: "Wüste, Felsen",            desc: "Heimatwelt der Twi'lek. Tidally locked – eine Seite immer Tag, eine immer Nacht." },
  { name: "Felucia",        grid: "Q-12", x: 0.7698, y: 0.2349, region: "Outer Rim",    terrain: "Pilzdschungel",            desc: "Bizarre, farbenfrohe Welt aus riesigen Pilzen und Pflanzen. Schwer umkämpft im Klonkrieg." },
  { name: "Mygeeto",        grid: "S-5",  x: 0.8206, y: 0.21, region: "Outer Rim",    terrain: "Eis, Kristalle",           desc: "Eisplanet der Muun-Bankiers. Reiche Kristallvorkommen. General Grievous' Schlachtort." },
  { name: "Saleucami",      grid: "Q-9",  x: 0.7993, y: 0.3371, region: "Outer Rim",    terrain: "Wüste, Krater",            desc: "Heißer Wüstenplanet. Schauplatz einer Klonkriegsschlacht. General Grievous floh hierher." },
  { name: "Crait",          grid: "L-19", x: 0.5928, y: 0.816, region: "Outer Rim",    terrain: "Salz, Kristalle",          desc: "Alter Rebellenstützpunkt, bedeckt mit weißem Salz und rotem Kristall darunter. Letzte Zuflucht der Resistance." },
  { name: "Batuu",          grid: "G-15", x: 0.3137, y: 0.6983, region: "Outer Rim",    terrain: "Wälder, Kavernen",         desc: "Abgelegener Außenposten am Rand des Unbekannten. Black Spire Outpost. Grenze zur Unbekannten Region." },
  { name: "Pasaana",        grid: "P-16", x: 0.6836, y: 0.7546, region: "Outer Rim",    terrain: "Wüste",                    desc: "Heimat des Aki-Aki-Festivals der Ahnen. Rey und Co. suchten hier nach Hinweisen auf Exegol." },
  { name: "Kijimi",         grid: "G-6",  x: 0.7711, y: 0.321, region: "Outer Rim",    terrain: "Schnee, Berge",            desc: "Bergplanet mit Schmugglernetz. Zerstört durch den Final-Order-Sternzerstörer." },
  { name: "Exegol",         grid: "unknown", x: 0.200, y: 0.750, region: "Unknown Regions", terrain: "Stürme, Wüste",       desc: "Geheimer Sith-Planet in der Unbekannten Region. Endgültige Heimat von Darth Sidious. Ort der letzten Schlacht." },

  // ── OUTER RIM – Fortsetzung ─────────────────────────────────────────
  { name: "Kamino",         grid: "S-20", x: 0.791, y: 0.6735, region: "Outer Rim",    terrain: "Ozean",                    desc: "Wasserplanet der Kaminoaner. Geheime Klonungswelt, die die Klonarmee für die Republik erschuf." },
  { name: "Dathomir",       grid: "O-7",  x: 0.6425, y: 0.3088, region: "Outer Rim",    terrain: "Dschungel, Sümpfe",        desc: "Dunkler Planet. Heimat der Dathomirianer und der Nacht-Schwestern. Geburtsort von Darth Maul." },
  { name: "Nal Hutta",      grid: "S-13", x: 0.7884, y: 0.5171, region: "Outer Rim",    terrain: "Sümpfe, Industrie",        desc: "Heimatwelt der Hutten. Korrupter, morastiger Planet. Hauptsitz des Hutten-Kartells." },
  { name: "Ord Ibanna",     grid: "S-13", x: 0.8205, y: 0.6092, region: "Outer Rim",    terrain: "Gasriese",                 desc: "Gasplanet nahe Nal Hutta. Teil des Huttensystems." },
  { name: "Florrum",        grid: "P-7",  x: 0.7747, y: 0.2148, region: "Outer Rim",    terrain: "Wüste, Schwefelfelder",    desc: "Hondo Onaka's Piratenplanet. Gelber Schwefelplanet mit Piraten-Stützpunkt." },
  { name: "Vanqor",         grid: "Q-8",  x: 0.7302, y: 0.3584, region: "Outer Rim",    terrain: "Wüste, Ruinen",            desc: "Wüstenplanet. Hondo nahm Anakin und Obi-Wan hier in der Serie gefangen." },
  { name: "Kadavo",         grid: "R-4",  x: 0.7763, y: 0.1609, region: "Outer Rim",    terrain: "Felsen, Minen",            desc: "Zygerrianischer Sklavenplanget. Sklavenkolonien der Zygerrianischen Sklavenhändler." },
  { name: "Zygerria",       grid: "R-4",  x: 0.7763, y: 0.1609, region: "Outer Rim",    terrain: "Wüste, Städte",            desc: "Heimatwelt der Zygerrianer. Das mächtigste Sklavenhändler-Imperium der Galaxis." },
  { name: "Carlac",         grid: "N-11", x: 0.4379, y: 0.2101, region: "Outer Rim",    terrain: "Schnee, Wälder",           desc: "Eiskalter Planet. Versteck von Death Watch unter Pre Vizsla." },
  { name: "Concordia",      grid: "O-7",  x: 0.6388, y: 0.2967, region: "Outer Rim",    terrain: "Wälder (Mond)",            desc: "Mond von Mandalore. Versteck und Trainingslager von Death Watch." },

  // ── OUTER RIM – Known from films/series ────────────────────────────
  { name: "Nevarro",        grid: "O-8",  x: 0.4532, y: 0.9172, region: "Outer Rim",    terrain: "Lava, Vulkane",            desc: "Kleiner Lavawelt-Planet. Stützpunkt der Bounty-Hunter-Gilde. Heimatplanet in The Mandalorian." },
  { name: "Sorgan",         grid: "L-16", x: 0.5053, y: 0.7518, region: "Outer Rim",    terrain: "Wälder, Reisfelder",       desc: "Ruhiger Waldplanet. Mando und Grogu verbrachten hier friedliche Zeit." },
  { name: "Trask",          grid: "P-11", x: 0.6843, y: 0.5062, region: "Outer Rim",    terrain: "Ozean, Hafen",             desc: "Ozean-Mond. Hafenstadt mit Bo-Katan Kryze und den Mandalorianern der Night Owls." },
  { name: "Tython",         grid: "L-9",  x: 0.4837, y: 0.4543, region: "Deep Core",    terrain: "Wälder, Ruinen",           desc: "Uralte Heimatwelt des Jedi-Ordens. Grogu rief hier durch die Macht nach Luke Skywalker." },
  { name: "Corvus",         grid: "M-14", x: 0.7827, y: 0.148, region: "Outer Rim",    terrain: "Verbrannte Wälder",        desc: "Verwüsteter Waldplanet. Ahsoka Tano suchte hier nach Morgan Elsbeth für Hinweise auf Thrawn." },
  { name: "Malachor",       grid: "S-16", x: 0.82, y: 0.7582, region: "Outer Rim",    terrain: "Zerstörte Oberfläche",     desc: "Gebrochener Planet, Stätte einer uralten Sith-Vernichtung. Letzter bekannter Ort eines Sith-Tempels." },
  { name: "Seelos",         grid: "P-16", x: 0.6067, y: 0.7258, region: "Outer Rim",    terrain: "Sümpfe, Schlamm",          desc: "Sumpfplanet. Versteck von Kommandant Rex und anderen Clone-Troopern nach dem Krieg." },

  // ── UNKNOWN REGIONS ────────────────────────────────────────────────
  { name: "Ahch-To",        grid: "F-13", x: 0.2293, y: 0.5937, region: "Unknown Regions", terrain: "Ozean, Inseln",         desc: "Geburtsplanet des Jedi-Ordens. Standort des ersten Jedi-Tempels. Lukes Exilort. Heilige Texte und Uneti-Baum." },
  { name: "Ilum",           grid: "H-3",  x: 0.3217, y: 0.0994, region: "Unknown Regions", terrain: "Eis, Kristallhöhlen",   desc: "Eisiger Planet mit Kyber-Kristall-Höhlen. Ritualstätte der Jedi. Umgebaut zur Starkiller-Basis." },
  { name: "Csilla",         grid: "G-2",  x: 0.2241, y: 0.3582, region: "Unknown Regions", terrain: "Eis, Untergrundstädte", desc: "Heimatwelt der Chiss. Hauptsitz der Chiss-Gemeinschaft. Geburtswelt von Grand Admiral Thrawn." },
  { name: "Rakata Prime",   grid: "M-22", x: 0.5463, y: 1.0491, region: "Unknown Regions", terrain: "Dschungel, Ruinen",     desc: "Heimatwelt der Rakata. Sitz des Unendlichen Imperiums (Legends). Ruinen einer uralten Zivilisation." },

  // ── OUTER RIM – Weitere Canon/Legends ──────────────────────────────
  { name: "Ossus",          grid: "R-7",  x: 0.7791, y: 0.3154, region: "Outer Rim",    terrain: "Wälder, Bibliotheken",     desc: "Ehemaliges Zentrum des Jedi-Wissens. Heimat der großen Jedi-Bibliothek, zerstört durch Sith-Invasion." },
  { name: "Dantooine",      grid: "O-11", x: 0.4723, y: 0.1454, region: "Outer Rim",    terrain: "Grasebenen, Wälder",       desc: "Friedlicher Agrarplanet. Früher Standort eines Jedi-Außenpostens und einer Rebellionsbasis." },
  { name: "Sullust",        grid: "R-19", x: 0.5473, y: 0.7943, region: "Outer Rim",    terrain: "Vulkane, Untergrundstädte", desc: "Vulkanplanet. Heimat der Sullustaner. Ort der Mustersungsflotte für die Endor-Attacke." },
  { name: "Christophsis",   grid: "L-10", x: 0.7322, y: 0.7454, region: "Outer Rim",    terrain: "Kristallstrukturen",       desc: "Schöner Kristallplanet. Frühe Klonkriegsschlacht. Anakin und Asokas erster Einsatz zusammen." },
  { name: "Rugosa",         grid: "Q-10", x: 0.73, y: 0.4578, region: "Outer Rim",    terrain: "Korallen, Wüste",          desc: "Korallenmond. Yoda verhandelte hier mit den Toydariern über einen Stützpunkt." },
  { name: "Kalee",          grid: "T-8",  x: 0.8654, y: 0.3576, region: "Outer Rim",    terrain: "Dschungel",                desc: "Heimatwelt von General Grievous. Wilder Dschungelplanet der Kaleesh." },
  { name: "Hypori",         grid: "T-9",  x: 0.8665, y: 0.4116, region: "Outer Rim",    terrain: "Industrie, Wüste",         desc: "Industrieller Planet. Grievous vernichtete hier eine Jedi-Einsatztruppe (Legends)." },
  { name: "Jabiim",         grid: "O-13", x: 0.8092, y: 0.3085, region: "Outer Rim",    terrain: "Matsch, Regen",            desc: "Düsterer Regenplanet. Heftig umkämpfte Klonkriegsschlacht. Planet wechselte mehrfach die Seiten." },
  { name: "Devaron",        grid: "P-11", x: 0.5169, y: 0.2025, region: "Outer Rim",    terrain: "Dschungel, Berge",         desc: "Heimatwelt der Devaronier. Alter Jedi-Tempel auf dem Planeten." },
  { name: "Iridonia",       grid: "Q-11", x: 0.4328, y: 0.2757, region: "Outer Rim",    terrain: "Felsen, Canyons",          desc: "Heimatwelt der Zabrak. Geburtsort von Darth Maul (Dathomir war nur sein Aufwachsort)." },
  { name: "Shili",          grid: "Q-10", x: 0.5099, y: 0.3245, region: "Outer Rim",    terrain: "Grasebenen, Wälder",       desc: "Heimatwelt der Togruta. Geburtsplanet von Ahsoka Tano." },
  { name: "Umbara",         grid: "N-13", x: 0.657, y: 0.4247, region: "Outer Rim",    terrain: "Dunkel, Biolumineszenz",   desc: "Planet ohne Sonnenlicht, bevölkert von Schattenlebewesen. Brutal umkämpft im Klonkrieg." },
  { name: "Kiros",          grid: "S-9",  x: 0.821, y: 0.4105, region: "Outer Rim",    terrain: "Wälder, Städte",           desc: "Bewohnter Planet. Zygerrianische Sklavenhändler verschleppten die gesamte Bevölkerung." },
  { name: "Toydaria",       grid: "S-11", x: 0.7744, y: 0.4999, region: "Hutt Space",   terrain: "Sümpfe",                   desc: "Heimatwelt der Toydarier. Watto, der Besitzer des jungen Anakin, war Toydarier." },
  { name: "Glee Anselm",    grid: "S-12", x: 0.4033, y: 0.3025, region: "Mid Rim",      terrain: "Ozean, Inseln",            desc: "Heimatwelt der Nautolaner. Geburtsplanet von Kit Fisto." },
  { name: "Dorin",          grid: "R-10", x: 0.4197, y: 0.324, region: "Outer Rim",    terrain: "Giftige Atmosphäre",       desc: "Heimatwelt der Kel Dor. Geburtsplanet von Plo Koon. Giftige Atmosphäre für andere Spezies." },
  { name: "Skako Minor",    grid: "Q-11", x: 0.7298, y: 0.5074, region: "Outer Rim",    terrain: "Städte, Säuremeere",       desc: "Technologischer Planet der Skakoaneer. Wichtige Waffenproduktion im Klonkrieg." },
  { name: "Bardotta",       grid: "P-10", x: 0.6845, y: 0.4566, region: "Outer Rim",    terrain: "Wälder, Tempel",           desc: "Spiritueller Planet. Repräsentant Jar Jar Binks wurde auf diplomatischer Mission hierher gesandt." },
  { name: "Takodana",       grid: "J-9",  x: 0.3837, y: 0.7315, region: "Mid Rim",      terrain: "Wälder, Seen",             desc: "Heimat von Maz Kanatas Burg. Einer der ältesten Wälder der Galaxis." },
  { name: "Cantonica",      grid: "S-4",  x: 0.7898, y: 0.143, region: "Outer Rim",    terrain: "Wüste",                    desc: "Wüstenplanet mit der opulenten Casino-Stadt Canto Bight. Heimat der Reichen und Kriegsprofiteure." },
  { name: "Wobani",         grid: "O-16", x: 0.6468, y: 0.7591, region: "Outer Rim",    terrain: "Grau, karg",               desc: "Gefängnisplanet des Imperiums. Jyn Erso wurde hier inhaftiert und von Rebellen befreit." },
  { name: "Vardos",         grid: "Q-16", x: 0.7291, y: 0.7558, region: "Outer Rim",    terrain: "Städte, Berge",            desc: "Imperiumstreuer Planet. Heimat von ISB-Agentin Iden Versio (Battlefront II)." },
  { name: "Pillio",         grid: "R-16", x: 0.7746, y: 0.757, region: "Outer Rim",    terrain: "Dschungel, Höhlen",        desc: "Dschungelplanet mit Observatorium von Palpatine. Luke Skywalker entdeckte hier ein Jedi-Artefakt." },
  { name: "Bracca",         grid: "O-15", x: 0.6678, y: 0.3735, region: "Outer Rim",    terrain: "Schrottplatz",             desc: "Schiffswrack-Planet. Cal Kestis arbeitete hier als Kabelklemmer, bevor er entdeckt wurde (Jedi: Fallen Order)." },
  { name: "Bogano",         grid: "N-15", x: 0.601, y: 0.1144, region: "Outer Rim",    terrain: "Wüste, Ruinen",            desc: "Abgelegener Planet mit uraltem Jedi-Gewölbe. Cal Kestis suchte hier nach einer Holokrone." },
  { name: "Zeffo",          grid: "P-14", x: 0.6839, y: 0.6553, region: "Outer Rim",    terrain: "Eis, Ruinen",              desc: "Eisiger Planet. Heimat der alten Zeffo-Zivilisation. Cal Kestis erforschte hier die Katakomben." },
  { name: "Nur",            grid: "R-17", x: 0.7744, y: 0.8067, region: "Outer Rim",    terrain: "Ozean, Inquisitorius",     desc: "Unterwasserfortung des Inquisitoriums. Versteck der Inquisitoren, die Jedi-Überlebende jagten." },
  { name: "Mapuzo",         grid: "L-14", x: 0.5305, y: 0.2986, region: "Outer Rim",    terrain: "Wüste, verlassene Städte", desc: "Verlassener Planet. Obi-Wan Kenobi und Leia versuchten hier, dem Imperium zu entkommen (Obi-Wan Serie)." },
  { name: "Jabiim",         grid: "O-13", x: 0.8092, y: 0.3085, region: "Outer Rim",    terrain: "Matsch, Industrie",        desc: "Industrieller Matschplanet. Obi-Wan und Leia wurden hier von den Inquisitoren gestellt." },
  { name: "Serenno",        grid: "N-5",  x: 0.5943, y: 0.2058, region: "Outer Rim",    terrain: "Wälder, Herrschaftssitze", desc: "Heimatwelt von Graf Dooku. Wohlhabender Adelsplanet der Separatisten-Führung." },
  { name: "Tellanroaeg",    grid: "N-14", x: 0.5929, y: 0.6529, region: "Outer Rim",    terrain: "Wälder",                   desc: "Bewaldeter Planet. Handelsrouten-Knotenpunkt." },

  // ── HUTT SPACE ─────────────────────────────────────────────────────
  { name: "Kintan",         grid: "S-12", x: 0.8234, y: 0.5576, region: "Hutt Space",   terrain: "Wüste, Felsen",            desc: "Heimatwelt der Nikto. Stark unter Hutten-Einfluss. Geburtsplanet von Bossk." },

  // ── WILD SPACE ─────────────────────────────────────────────────────
  { name: "Lasan",          grid: "F-16", x: 0.4137, y: 0.2089, region: "Wild Space",   terrain: "Grasebenen, Wälder",       desc: "Heimatwelt der Lasat. Zerstört durch den imperialen General Kallus. Zeb Orrelios ist einer der letzten Überlebenden." },
  { name: "Lira San",       grid: "B-19", x: 0.0465, y: 0.887, region: "Wild Space",   terrain: "Unbekannt",                desc: "Sagenumwobene ursprüngliche Heimatwelt der Lasat. Versteckt im Wildraum." },

  // Manuell kalibriert
  { name: "Aduba", grid: "?", x: 0.8841, y: 0.4735, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Agamar", grid: "?", x: 0.5449, y: 0.2148, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Alui", grid: "?", x: 0.617, y: 0.7701, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Antar", grid: "?", x: 0.6048, y: 0.5182, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Anzat", grid: "?", x: 0.779, y: 0.3152, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Askaj", grid: "?", x: 0.5322, y: 0.9319, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Baros", grid: "?", x: 0.893, y: 0.2999, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Besberra", grid: "?", x: 0.4969, y: 0.9237, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Bormter", grid: "?", x: 0.31, y: 0.6402, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Carratos", grid: "?", x: 0.4451, y: 0.3574, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Cerea", grid: "?", x: 0.3773, y: 0.7392, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Charros", grid: "?", x: 0.7498, y: 0.3819, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Codia", grid: "?", x: 0.3328, y: 0.6701, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Columnex", grid: "?", x: 0.7752, y: 0.2596, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Commenor", grid: "?", x: 0.5817, y: 0.4658, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Cona", grid: "?", x: 0.6236, y: 0.4745, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Corva Yag", grid: "?", x: 0.5755, y: 0.9174, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Cyphar", grid: "?", x: 0.4872, y: 0.7781, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Doldur", grid: "?", x: 0.6705, y: 0.6713, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Dolla", grid: "?", x: 0.4906, y: 0.8268, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Droxu", grid: "?", x: 0.8672, y: 0.4871, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Du Hutta", grid: "?", x: 0.7917, y: 0.5009, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Eclipse", grid: "?", x: 0.524, y: 0.5023, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Eriadu", grid: "?", x: 0.5469, y: 0.8175, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Euceron", grid: "?", x: 0.7416, y: 0.3131, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Excarga", grid: "?", x: 0.8377, y: 0.7375, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Firrerre", grid: "?", x: 0.3226, y: 0.7341, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Florn", grid: "?", x: 0.8331, y: 0.2048, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Foless", grid: "?", x: 0.5298, y: 0.6083, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Gamorr", grid: "?", x: 0.8455, y: 0.6263, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Gannaria", grid: "?", x: 0.317, y: 0.6809, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Giaca", grid: "?", x: 0.2178, y: 0.6082, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Gwar", grid: "?", x: 0.3416, y: 0.6919, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Houche", grid: "?", x: 0.33, y: 0.7204, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Imynusoph", grid: "?", x: 0.4336, y: 0.9615, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Kabal", grid: "?", x: 0.5806, y: 0.8287, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Kal'Shebbol", grid: "?", x: 0.5508, y: 0.9618, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Kalist", grid: "?", x: 0.4776, y: 0.513, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Kampe", grid: "?", x: 0.5002, y: 0.5094, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Kesh", grid: "?", x: 0.9066, y: 0.4242, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Kinooine", grid: "?", x: 0.3963, y: 0.9717, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Kinoss", grid: "?", x: 0.1993, y: 0.3578, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Lorell", grid: "?", x: 0.6321, y: 0.4105, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Malagarr", grid: "?", x: 0.917, y: 0.3389, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Manpha", grid: "?", x: 0.4445, y: 0.9082, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Medth", grid: "?", x: 0.5467, y: 0.7701, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Mon Gazza", grid: "?", x: 0.7084, y: 0.7152, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Murkhana", grid: "?", x: 0.8008, y: 0.2618, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Mykapo", grid: "?", x: 0.871, y: 0.2885, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Mytus", grid: "?", x: 0.8014, y: 0.0951, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Namadii", grid: "?", x: 0.3904, y: 0.2658, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Naos", grid: "?", x: 0.8128, y: 0.8101, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Near Pando", grid: "?", x: 0.8198, y: 0.6172, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Nopsin", grid: "?", x: 0.3684, y: 0.6998, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Novarro", grid: "?", x: 0.467, y: 0.9262, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "O'reen", grid: "?", x: 0.3037, y: 0.597, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Odessen", grid: "?", x: 0.2895, y: 0.6517, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Odik", grid: "?", x: 0.4503, y: 0.4688, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Omwat", grid: "?", x: 0.5778, y: 0.8054, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Ord Cestus", grid: "?", x: 0.6275, y: 0.2262, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Pakuuni", grid: "?", x: 0.851, y: 0.2303, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Parcelus", grid: "?", x: 0.6221, y: 0.5418, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Pergitor", grid: "?", x: 0.55, y: 0.9408, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Ponemah", grid: "?", x: 0.3492, y: 0.7401, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Quellor", grid: "?", x: 0.5833, y: 0.5207, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Quethold", grid: "?", x: 0.3026, y: 0.2291, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Relatta", grid: "?", x: 0.5797, y: 0.3611, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Reytha", grid: "?", x: 0.6249, y: 0.5149, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Rhand", grid: "?", x: 0.127, y: 0.4728, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Riette", grid: "?", x: 0.2126, y: 0.2652, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Rinn", grid: "?", x: 0.8831, y: 0.5198, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Roon", grid: "?", x: 0.7856, y: 0.6996, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Rutan", grid: "?", x: 0.4836, y: 0.9094, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Shedu Maad", grid: "?", x: 0.6379, y: 0.3824, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Shiva", grid: "?", x: 0.4909, y: 0.9611, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Shogun", grid: "?", x: 0.6491, y: 0.8477, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Shree", grid: "?", x: 0.1111, y: 0.7327, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Skynara", grid: "?", x: 0.6894, y: 0.8669, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Socorro", grid: "?", x: 0.7032, y: 0.7884, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Subterrel", grid: "?", x: 0.4853, y: 0.9473, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Svivren", grid: "?", x: 0.6355, y: 0.8736, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Swellen", grid: "?", x: 0.5208, y: 0.9061, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Taloraan", grid: "?", x: 0.3781, y: 0.6642, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Tangrene", grid: "?", x: 0.6349, y: 0.1724, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Terminus", grid: "?", x: 0.448, y: 0.9465, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Ton-Falk", grid: "?", x: 0.8426, y: 0.2166, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Tosste", grid: "?", x: 0.4941, y: 0.8966, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Trogan", grid: "?", x: 0.7736, y: 0.2807, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Usk", grid: "?", x: 0.8411, y: 0.4586, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Vestar", grid: "?", x: 0.5922, y: 0.934, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Vobati", grid: "?", x: 0.4023, y: 0.4628, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Xerton", grid: "?", x: 0.4188, y: 0.0945, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Yag'Dhul", grid: "?", x: 0.5174, y: 0.6538, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Zeltros", grid: "?", x: 0.6356, y: 0.4498, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Zemiah's Den", grid: "?", x: 0.4143, y: 0.5191, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Zeta", grid: "?", x: 0.4473, y: 0.06, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Zirulast", grid: "?", x: 0.6586, y: 0.4696, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
  { name: "Zonju", grid: "?", x: 0.4232, y: 0.9754, region: "Unknown", terrain: "Unbekannt", desc: "Manuell kalibriert." },
];

// Hilfsfunktion: Grid-Koordinate in numerische X/Y umrechnen
function gridToCoords(grid) {
  if (!grid || grid === "unknown") return null;
  const letter = grid[0].toUpperCase();
  const num = parseInt(grid.slice(2));
  const x = (letter.charCodeAt(0) - 'A'.charCodeAt(0)) / 21; // A=0, V=1
  const y = (num - 1) / 20; // 1=0, 20=1
  return { gridX: x, gridY: y };
}
